services:
  tftp:
    build: .
    container_name: tftp-server
    image: kaczmar2/tftp-hpa
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ:-UTC}  # Use .env file or default to UTC
    volumes:
      - ${TFTP_ROOT:-/srv/docker/tftp}:/srv/tftp
      - /etc/localtime:/etc/localtime:ro
