name: Docker Build, Test and Publish

on:
  push:
    branches: [ main ]
    tags: 
      - v*
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Install TFTP client
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq tftp-hpa
      
    - name: Build Docker image (single platform for testing)
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: false
        tags: kaczmar2/tftp-hpa:test
        load: true
        
    - name: Set up TFTP test environment
      run: |
        # Set up Docker bind mount
        sudo mkdir -p /srv/docker/tftp
        sudo chown -R $USER:$USER /srv/docker
        sudo chmod -R 755 /srv/docker/tftp
        
    - name: Test image can start
      run: |
        # Start container
        docker run -d \
          --name tftp-test \
          --network host \
          -e TZ=America/Denver \
          -v /srv/docker/tftp:/srv/tftp \
          kaczmar2/tftp-hpa:test
          
        # Wait for startup
        sleep 3
        
        # Check if container is running
        docker ps | grep tftp-test
        
        # Check logs for startup message
        docker logs tftp-test | grep "Starting tftpd"
        
    - name: Test TFTP functionality
      run: |
        cd /tmp
        uname -a | sudo tee /srv/docker/tftp/test
        
        # Test TFTP download
        echo "get test" | tftp localhost
        
        # Verify file was downloaded and content matches
        if [ -f test ]; then
          echo "✅ File downloaded successfully"
          if diff test /srv/docker/tftp/test; then
            echo "✅ File content matches"
          else
            echo "❌ File content differs"
            echo "Downloaded file:"
            cat test
            echo "Original file:"
            cat /srv/docker/tftp/test
            exit 1
          fi
        else
          echo "❌ File was not downloaded"
          exit 1
        fi

    - name: Test TFTP custom options (PUT functionality)
      run: |
        # Stop existing container
        docker stop tftp-test || true
        docker rm tftp-test || true
        
        # Start container with --create flag to enable uploads
        docker run -d \
          --name tftp-test \
          --network host \
          -v /srv/docker/tftp:/srv/tftp \
          -e TFTP_ARGS="--foreground --secure --create --verbosity 4 --user tftp" \
          kaczmar2/tftp-hpa:test
        
        # Wait for container to be ready
        sleep 3
        
        # Test TFTP upload (PUT)
        cd /tmp
        echo "Upload test file content" > upload-test.txt
        
        # Upload file via TFTP
        echo -e "binary\nput upload-test.txt" | tftp localhost
        
        # Verify file was uploaded to server
        if [ -f /srv/docker/tftp/upload-test.txt ]; then
          echo "✅ File uploaded successfully"
          if grep -q "Upload test file content" /srv/docker/tftp/upload-test.txt; then
            echo "✅ Uploaded file content is correct"
          else
            echo "❌ Uploaded file content is incorrect"
            echo "Expected: Upload test file content"
            echo "Actual:"
            cat /srv/docker/tftp/upload-test.txt
            exit 1
          fi
        else
          echo "❌ File was not uploaded"
          ls -la /srv/docker/tftp/
          exit 1
        fi
        
        # Clean up uploaded test file
        sudo rm -f /srv/docker/tftp/upload-test.txt
        
        # Check TFTP logs for request
        docker logs tftp-test | grep "RRQ from"
        
    - name: Cleanup
      if: always()
      run: |
        docker stop tftp-test || true
        docker rm tftp-test || true
        rm -f /tmp/test

    - name: Login to Docker Hub
      if: startsWith(github.ref, 'refs/tags/v')
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      if: startsWith(github.ref, 'refs/tags/v')
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: kaczmar2/tftp-hpa
        tags: |
          type=semver,pattern={{version}}

    - name: Build and push to Docker Hub
      if: startsWith(github.ref, 'refs/tags/v')
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}